diff a/os/Makefile b/os/Makefile	(rejected hunks)
@@ -27,11 +27,11 @@ DISASM ?= -x
 
 build: env $(KERNEL_BIN)
 
-env:
-	(rustup target list | grep "riscv64gc-unknown-none-elf (installed)") || rustup target add $(TARGET)
-	cargo install cargo-binutils
-	rustup component add rust-src
-	rustup component add llvm-tools-preview
+env:	
+#	(rustup target list | grep "riscv64gc-unknown-none-elf (installed)") || rustup target add $(TARGET)
+#	cargo install cargo-binutils
+#	rustup component add rust-src
+#	rustup component add llvm-tools-preview
 
 $(KERNEL_BIN): kernel
 	@$(OBJCOPY) $(KERNEL_ELF) --strip-all -O binary $@
