diff a/os/Makefile b/os/Makefile	(rejected hunks)
@@ -5,16 +5,16 @@ KERNEL_ELF := target/$(TARGET)/$(MODE)/os
 KERNEL_BIN := $(KERNEL_ELF).bin
 DISASM_TMP := target/$(TARGET)/$(MODE)/asm
 
-# Building mode argument
-ifeq ($(MODE), release)
-	MODE_ARG := --release
-endif
-
 # BOARD
 BOARD := qemu
 SBI ?= rustsbi
 BOOTLOADER := ../bootloader/$(SBI)-$(BOARD).bin
 
+# Building mode argument
+ifeq ($(MODE), release)
+	MODE_ARG := --release
+endif
+
 # KERNEL ENTRY
 KERNEL_ENTRY_PA := 0x80200000
 
@@ -28,10 +28,10 @@ DISASM ?= -x
 build: env $(KERNEL_BIN)
 
 env:
-#	(rustup target list | grep "riscv64gc-unknown-none-elf (installed)") || rustup target add $(TARGET)
-#	cargo install cargo-binutils
-#	rustup component add rust-src
-#	rustup component add llvm-tools-preview
+	(rustup target list | grep "riscv64gc-unknown-none-elf (installed)") || rustup target add $(TARGET)
+	cargo install cargo-binutils
+	rustup component add rust-src
+	rustup component add llvm-tools-preview
 
 $(KERNEL_BIN): kernel
 	@$(OBJCOPY) $(KERNEL_ELF) --strip-all -O binary $@
@@ -43,7 +43,6 @@ kernel:
 	@cargo build $(MODE_ARG)
 	@rm src/linker.ld
 
-
 clean:
 	@cargo clean
 
@@ -57,6 +56,8 @@ disasm-vim: kernel
 
 run: run-inner
 
+	
+
 run-inner: build
 	@qemu-system-riscv64 \
 		-machine virt \
